# Generated by Django 3.2.2 on 2021-05-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, unique=True, verbose_name='Team Name')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_played', models.IntegerField()),
                ('total_points_scored', models.IntegerField()),
                ('total_close_victories', models.IntegerField()),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='soccer_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_result', models.CharField(blank=True, choices=[('won', '2'), ('draw', '1'), ('lost', '0')], default='', max_length=30, verbose_name='Match Result')),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='soccer_app.player')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='soccer_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ManyToManyField(to='soccer_app.Team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchtype', models.CharField(blank=True, choices=[('onevsone', '1vs1'), ('twovstwo', '2vs2'), ('onevstwo', '1vs2'), ('threevsthree', '3vs3')], default='', max_length=30, verbose_name='Match Type')),
                ('first_team_name', models.ManyToManyField(related_name='first_team_name', to='soccer_app.Team', verbose_name='Team1 Name')),
                ('second_team_name', models.ManyToManyField(related_name='second_team_name', to='soccer_app.Team', verbose_name='Team2 Name')),
            ],
        ),
    ]
